/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package edu.lmu.bfs.ase2.swing.gui;

import java.awt.Dimension;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import edu.lmu.bfs.ase2.model.UserStory;
import edu.lmu.bfs.ase2.service.UserStoryService;
import edu.lmu.bfs.ase2.swing.TaskListPanel;

/**
 *
 * @author bamo
 */
public class UserStoryDetailsPanel extends javax.swing.JPanel {

    /**
	 * 
	 */
	private static final long serialVersionUID = -1161169818048972131L;
	/**
     * Creates new form UserStoryDetails
     */
    public UserStoryDetailsPanel(int id) {
    	if (!(id >0)) {
			id =1;
		}
    	userStoryService = new UserStoryService();
    	userStory = (UserStory) userStoryService.getUserStoryById(id);
    	
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
                        
    private void initComponents() {
    	
    	this.setMaximumSize(new Dimension(500,400));
    	setPreferredSize(new Dimension(500,400));

        tittleField = new javax.swing.JTextField();
       
        jScrollPane1 = new javax.swing.JScrollPane();
        decsriptionTextArea = new javax.swing.JTextArea();
        decsriptionTextArea.setLineWrap(true);
        decsriptionTextArea.setWrapStyleWord(true);
        jScrollPane2 = new javax.swing.JScrollPane();
        acceptanceCriteriaTextArea = new javax.swing.JTextArea();
        acceptanceCriteriaTextArea.setLineWrap(true);
        acceptanceCriteriaTextArea.setWrapStyleWord(true);
        titleLabel = new javax.swing.JLabel();
        decriptionLabel = new javax.swing.JLabel();
        acceptanceCriteriaLabel = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        taskButton = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tittleField.setText(userStory.getTitle());

        decsriptionTextArea.setColumns(20);
        decsriptionTextArea.setRows(5);
        decsriptionTextArea.setText(userStory.getDescription());
        jScrollPane1.setViewportView(decsriptionTextArea);

        acceptanceCriteriaTextArea.setColumns(20);
        acceptanceCriteriaTextArea.setRows(5);
        acceptanceCriteriaTextArea.setText(userStory.getAcceptanceCriteria());
        jScrollPane2.setViewportView(acceptanceCriteriaTextArea);

        titleLabel.setText("Title");

        decriptionLabel.setText("Description");

        acceptanceCriteriaLabel.setText("Acceptance Criteria");

        buttonPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(0));

        addButton.setText("Add new");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        removeButton.setText("Remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });
        
        taskButton.setText("View task");
        taskButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTaskButtonActionPerformed(evt);
            }
        });
        

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(taskButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addButton, removeButton, saveButton, taskButton});

        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(saveButton)
                    .addComponent(removeButton)
                    .addComponent(taskButton))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(decriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(acceptanceCriteriaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tittleField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2))
                .addContainerGap())
            .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(tittleField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(titleLabel)
                        .addGap(39, 39, 39)
                        .addComponent(decriptionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(acceptanceCriteriaLabel)
                        .addGap(123, 123, 123)))
                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>                        

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }   
    

	private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        String message = " Are you sure you want to remove user story? ";
        String title = "Remove";
        int reply = JOptionPane.showConfirmDialog(this, message, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
        	userStoryService.delete(userStory);
        	
		}
    } 

	private void addNewButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
		new AddUserStoryPanel().display();
    }
	private void viewTaskButtonActionPerformed(java.awt.event.ActionEvent evt) { 
		if (userStory.hasTask()) {
			new TaskListPanel(null, userStory).display();
		}else{
			String message = "User story has no tasks yet!";
			String title = "Information";
			JOptionPane.showMessageDialog(this, message, title, JOptionPane.INFORMATION_MESSAGE);
		}
		
    }
	
    public static void main(String [] args){
    	UserStoryDetailsPanel u = new UserStoryDetailsPanel(0);
    	JFrame f = new JFrame();
    	f.add(u);
    	f.setVisible(true);
    	f.pack();
    	f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }
    // Variables declaration - do not modify                     
    private javax.swing.JLabel acceptanceCriteriaLabel;
    private javax.swing.JButton addButton;
    private javax.swing.JLabel decriptionLabel;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea decsriptionTextArea;
    private javax.swing.JTextArea acceptanceCriteriaTextArea;
    private javax.swing.JTextField tittleField;
    private javax.swing.JButton removeButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton taskButton;
    private javax.swing.JLabel titleLabel;
    private UserStory userStory;
    private UserStoryService userStoryService;
    // End of variables declaration                   
}
